// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUgjlIIplU2Mh92HIUKcU-40pdb-ihy2Q',
    appId: '1:178608959958:web:3129244895b32ab53df477',
    messagingSenderId: '178608959958',
    projectId: 'animanager-805bc',
    authDomain: 'animanager-805bc.firebaseapp.com',
    storageBucket: 'animanager-805bc.firebasestorage.app',
    measurementId: 'G-1DXE1W9QE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCumUt6xVRFjnmeNu0aHJDHnM65s3uPTpI',
    appId: '1:178608959958:android:48392f185482ea9c3df477',
    messagingSenderId: '178608959958',
    projectId: 'animanager-805bc',
    storageBucket: 'animanager-805bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkTouyOmIUryjFZsI18fN4pUxILoIO7Jg',
    appId: '1:178608959958:ios:d387b32cc6b043453df477',
    messagingSenderId: '178608959958',
    projectId: 'animanager-805bc',
    storageBucket: 'animanager-805bc.firebasestorage.app',
    iosBundleId: 'com.example.animanager',
  );

}